### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by Tox86** [murrty/youtube-dl-gui#1]
That is a bug:

![lol](https://user-images.githubusercontent.com/7013508/35944119-29544300-0c3a-11e8-9fa7-431de4a2f1ba.PNG)

Cheers

**Comment by murrty** [comment]
I wanted to use decimal as a replacement for string version checking as it is much cleaner, but I guess it doesn't parse periods as decimals in metric. I'll switch to int as it's not as clean but much cleaner than a string, but I'll look around to see if I can get decimal to work with metric.

**Comment by Tox86** [comment]
Comvert Class?

**Comment by murrty** [comment]
When you have a chance, can you try running this:
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/1710909/youtube-dl-gui.zip)

It should fix it.

**Comment by murrty** [comment]
fixed in 1.69
