### ISSUE TITLE
choosing resolution for video

### ISSUE THREAD

**Issue by DajMiliona** [murrty/youtube-dl-gui#10]
Pleasee add option choosing resolution for video
Program always download in best. For peophe who have limited internet, or less conection it is not good solution. Please add option asking about resolution from avaible. Options in the GUI. I do not like the command line.

**Comment by murrty** [comment]
Added in latest release (2.1)

**Comment by murrty** [comment]
I would also like to point out that I have a data cap, and to prevent my bill from going above any crazy limit I can only test so many qualities before it becomes problematic. If there are any problematic qualities, please create a new issue and tell me which ones.
