### ISSUE TITLE
Can't find how to enter a login and password for youtube

### ISSUE THREAD

**Issue by chp-1960** [murrty/youtube-dl-gui#101]
Hi,
I'm trying to DL videos from youtube which require me to enter my login and password to confirm my age.
But I can't find where to enter a login and password for these videos in youtube-dl-gui for Windows (32 & 64bits).
I saw this option exist since version 2.5.x.
Was it removed or Can someone tell me how / where to find it?

**Comment by murrty** [comment]
You mean download with authentication?

You could also use yt-dlp, which bypasses login requirements... for now.

**Comment by chp-1960** [comment]
Many Thanks man for your fast reply.
It works like a charm after I configured Youtube-dl-gui to use yt-dlp. I was able to dl the files
