### ISSUE TITLE
Program crash with static yt-dlp.exe

### ISSUE THREAD

**Issue by ask2018** [murrty/youtube-dl-gui#103]
Hi,
it is not possible to set static yt-dlp.exe path in the settings. If I'll set it,  program just crashes with no specific error after restart.

**Comment by murrty** [comment]
I tested it by moving yt-dlp to a different drive and different name, but could not replicate this issue. It's probably an issue with your configuration or your current setup.

**Comment by ask2018** [comment]
Yeah it really seems to be related to my config. I've deleted all config files and started with fresh one and now there is no more crash.
