### ISSUE TITLE
Move language files to translation host (like Transiflex)

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#104]
@murrty 

What do you think to move language files to host specfic for translation like Transiflex?

Many benefits for translator (like advise automatically for changes).

Thanks.

**Comment by murrty** [comment]
I'm not really interested in using another service to work with translations. My method probably isn't the best, but I don't really have to pay for it.

**Comment by bovirus** [comment]
@nurrty

Why pay for it? It's free.
And it's used with many benfits by a lot of freeware software.

**Comment by murrty** [comment]
Not currently interested in moving localization outside of Github at the time being.
