### ISSUE TITLE
Check for updates not working?

### ISSUE THREAD

**Issue by SGvagon** [murrty/youtube-dl-gui#105]
Hello,

when I try check for updates of this program, it shows only error message for manual check update

![Yt_dl_gui_check_updates](https://user-images.githubusercontent.com/14125053/141401863-b61f23e6-e747-4e8d-870c-d18095cd6d19.png)

It is not issue for me, program works properly, but I must checking for updates manually here on Github.

Thank you in advance.

**Comment by murrty** [comment]
Is it blocked in the firewall?

**Comment by SGvagon** [comment]
I tried completely turn off Windows firewall, but checking update shows same error.

**Comment by murrty** [comment]
here's a build based (mostly) on the latest commit, the only change is that when that message appears, your clipboard will get some text put into it. If you get it again, put the contents into pastebin, it should help diagnose the problem.

[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/7575672/youtube-dl-gui.zip)

**Comment by SGvagon** [comment]
After download this version, I can't open it. It only shows info message window about usage the program and piracy. Then choose download folder and that's it, the program does not start.

**Comment by murrty** [comment]
strange. try this one
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/7576188/youtube-dl-gui.zip)

**Comment by SGvagon** [comment]
Yes, this version start up. Here is the Error code https://pastebin.com/YyVpruPw . I think, there is a problem with clipboard function, so this error is not about the Check update feature. Becaue nohing sent to my system clipboard.

**Comment by murrty** [comment]
That shouldn't be occurring at all. STAThread was already specified:

https://github.com/murrty/youtube-dl-gui/blob/b4b454052c62265c6055f02a63373ad5366186fe/Program.cs#L24

This one removed the clipboard stuff and is the latest commit.
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/7577712/youtube-dl-gui.zip)

**Comment by SGvagon** [comment]
Now I see the message, that I have to paste to pastebin, but still I haven't got any text in clipboard. I tried run youtube-dl gui as Administrator too, but nothing change. 
![Clipboard_issue](https://user-images.githubusercontent.com/14125053/142808358-cbeadd89-6674-4a23-9b56-df58e1e860f4.png)

**Comment by murrty** [comment]
Yeah, I might have forgot to remove that message from the message box. Considering, I need to handle that problem more effectively.

This build should be more helpful, and give more relevant information.
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/7580255/youtube-dl-gui.zip)

**Comment by SGvagon** [comment]
Ok here is the error code https://pastebin.com/CzWLAaXP .

**Comment by murrty** [comment]
What happens if you go to https://api.github.com/repos/murrty/youtube-dl-gui/releases/latest in a browser?

**Comment by SGvagon** [comment]
I see JSON here is a screenshot https://i.postimg.cc/6QQfj9k9/screenshot-46.png .
Or here is all raw data https://pastebin.com/3AhtfJTH .

**Comment by murrty** [comment]
Hey, try the pre-release. It should give more information to better debug it, now.

**Comment by SGvagon** [comment]
Yes, here is a error code https://pastebin.com/aHwe78LG .

**Comment by murrty** [comment]
I see that it's retrieving the XML document right. The exception you just got was, while unexpected, understandable that it happened.

Try the pre-release again, I updated the binaries. Hopefully it should say an update is available, or not.

**Comment by SGvagon** [comment]
No, I see the error again and then Update check failed.

**Comment by murrty** [comment]
I'll be honest, I can't do much more now. I can't reproduce it. I have one last option, if you're running it in portable mode, can you send me the ini file? if you don't have one, you can generate it by going into the last tab in the settings.

**Comment by SGvagon** [comment]
I only downloading your updated versions and run them as a first time (I delete app data in %local% first) . If it this last version should work, I could try it on a different machine. I am using W7 PRO x64 bit if this help.

**Comment by SGvagon** [comment]
No, I tried this pre-release on two more Windows 7 machines, but I still have the error and then Update check failed. But here is the portable ini file [settings.zip](https://github.com/murrty/youtube-dl-gui/files/7600666/settings.zip) .

**Comment by murrty** [comment]
Yeah, I can't reproduce this issue. I tried it on a Windows 7 VM but it worked. So it seems like something in your specific instance is not working properly, and I can't diagnose it further at this moment.

**Comment by murrty** [comment]
Here, I think this will fix it. Sort-of hacky, but if it works...
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/7601457/youtube-dl-gui.zip)

**Comment by SGvagon** [comment]
Yes, this working perfectly :-) . With changelog too, nice work.

**Comment by murrty** [comment]
Good. I'll need to do some work on making it compatible, because I am anticipating parsing issues if it goes onto a release version, since checking for beta (or on beta versions at all) compare the versions as literal words.

Still, I have no idea why it would have issues without the culture information when checking it outside of the decimal parser.

Thanks for testing all these builds.
