### ISSUE TITLE
360 video problems

### ISSUE THREAD

**Issue by ktrece** [murrty/youtube-dl-gui#109]
hello i have this problem when i download a 360 4k video, the videos are downloaded "broken" can you help me download it well?¿
![Captura](https://user-images.githubusercontent.com/96886228/147779877-7e2b2e54-2a1d-49fa-9203-e3adb888b386.JPG)
![Captura2](https://user-images.githubusercontent.com/96886228/147779879-2b8e2a70-e7c4-4ad3-b808-ba17a1ca01c2.JPG)

**Comment by murrty** [comment]
I don't know what's considered broken here, I don't know what a 360° video source should look like. Whatever the case, I don't think it's because this program is causing it, it might be whatever version of youtube-dl you're using.
