### ISSUE TITLE
Can't (re)download youtube-dl in version 2.27

### ISSUE THREAD

**Issue by SGvagon** [murrty/youtube-dl-gui#110]
Hello,

after udpate to the new version, I can't download youtube-dlp from settings menu. After click on (re)download button it shows error table with An exception has occured:

here is the error code: https://pastebin.com/KjBHkh7K .

So I had to download youtube-dlp anf ffmpeg manually and set path to the folder in settings to work properly.

Thank you in advance.

**Comment by murrty** [comment]
i had it in as a test for throwing an out of bounds exception, one blue moon ago, but then forgot about it.
