### ISSUE TITLE
Make it easy to register many URLs as a list with bacth download.

### ISSUE THREAD

**Issue by ni1chigo2115** [murrty/youtube-dl-gui#111]
I sometimes use this app to download hundreds of URLs, but it is hard to stick each URL one by one.
Is it possible to make it so that I can register multiple lines?

**Comment by murrty** [comment]
An import feature? It's possible, but if they're all going to be the same, try the batch download on the main form (the download button, click the drop-down arrow), that should make it easier to do.

**Comment by murrty** [comment]
Since some prerelease version ago, batch download got a feature to import links from a file/clipboard, as well as clipboard monitoring for URLs.
