### ISSUE TITLE
When using Youtube-dlp, "best" quality downloads at no higher than 1080p

### ISSUE THREAD

**Issue by yt-bug** [murrty/youtube-dl-gui#112]
I think some argument syntax has been changed since youtube-dl, because selecting "custom", and leaving the arguments box blank to use defaults lets me download the video at 8k/4k etc. maximum resolution/quality with no issues.

**Comment by murrty** [comment]
does this issue effect 2.26X?

**Comment by murrty** [comment]
This issue may have been fixed in the latest update, if it is, please close the issue.

**Comment by yt-bug** [comment]
It's working now! Thank you!
