### ISSUE TITLE
"Cannot start process because a file name has not been provided" error

### ISSUE THREAD

**Issue by plissken1138** [murrty/youtube-dl-gui#115]
Updated from 2.27 to 2.3 and getting this error persistently on first download after every program startup.
On second try with same YT link, without changing anything, it downloads OK.
Below is data from log window:

An exception occured.

Message: Cannot start process because a file name has not been provided.
Stacktrace:    at System.Diagnostics.Process.Start()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass11_0.<BeginDownload>b__0()
Source: System
Target Site: Boolean Start()
Inner Exception: 

========== FULL REPORT ==========
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass11_0.<BeginDownload>b__0()
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current version: 2.3
Current culture: English (United States)
OS: Version: 10.0.19044
Service Pack Major: 0
Service Pack Minor: 0
System Caption: Microsoft Windows 10 Education

**Comment by bw4518** [comment]
Yeah, same here.

**Comment by murrty** [comment]
are you using a static youtube-dl location?

**Comment by murrty** [comment]
If you run youtube-dl-gui with youtube-dl in the same directory and static youtube-dl disabled, does it still occur?

**Comment by Bonoboo** [comment]
For more explicit info I used powerful Process Monitor by Sysinternals. It shows all files that application tries access to.
This screenshot shows situation if try to download video after "cold" app start:
![1-error](https://user-images.githubusercontent.com/6930109/185301993-5e9b8a14-b27d-4d4c-9e10-1b2c5130b0e4.png)

This screenshot at second successful try:
![2-ok](https://user-images.githubusercontent.com/6930109/185302000-ea059f59-91ae-48f0-ba76-36f60309bdd9.png)

As you can see problem somehow related to Microsoft .NET Framework. Files can't be found, but then app ignores them.

**Comment by Bonoboo** [comment]
Oh, wait, .NET seems not related here. Now I monitored processes operations.
And at error `youtube-dl-gui.exe` even not tries to launch `yt-dlp.exe` with arguments.

This screenshot shows situation if try to download video after "cold" app start. Take a note on "Load image".
![1-bug](https://user-images.githubusercontent.com/6930109/185303619-3103bb64-3b41-4ae0-b1d2-dd5df9188d58.png)

This screenshot at second successful try. No "Load image" operation.
![2-ok](https://user-images.githubusercontent.com/6930109/185303638-2087233d-479a-4cd6-a47c-d85fc40f3ede.png)

**Comment by murrty** [comment]
By any chance, does the first instance have the message "Rescan finished and found, continuing" within the output window?

**Comment by murrty** [comment]
I have to assume that it does send that message. Try the latest version, and if it doesn't work, well then gosh darn it.

**Comment by murrty** [comment]
Closed due to not being able to replicated and no additional data being provided. Re-open if it persists.

**Comment by bw4518** [comment]
Ditching the old settings.ini seems to have helped here.
