### ISSUE TITLE
Request for an auto import feature from the clipboard for batch downloads

### ISSUE THREAD

**Issue by ErikBrown2** [murrty/youtube-dl-gui#116]
Would it be possible to add an auto URL import feature from the clipboard for the Batch download? Similar to the reading of the clipboard when you hover with the mouse over the textbox for single downloads. But then without the need to hover with the mouse over the textbox. This will make it much easier to add a high number of URLs to the batch download option.

What I mean is the following:

- The user selects the batch download menu option
- The user enables this new clipboard monitoring option
- The user copies a URL from a video to the clipboard
- Youtube-dl-gui detects the new string on the clipboard and imports it
- Youtube-dl-gui will do a simple validation to make sure that the imported string is a valid URL
- Youtube-dl-gui adds the URL to the list of to-be-downloaded URLs
- Youtube-dl-gui clears the clipboard
- A short beep will sound to inform the user that the URL has been successfully added (because the user does not watch the Youtube-dl-gui window)
- Youtube-dl-gui continues to monitor the clipboard for more URLs till the user starts the downloads

**Comment by murrty** [comment]
I'm not very keen on allowing the program monitor the users' clipboard, even with explicit consent every time the users requests it, it would be easy to flag the program as malicious in that case. But I can see what I can do.

In the meantime, you can congregate a list of links on a notepad instance and import them to the batch downloader (on version 2.31-pre1+). Probably not what you're hoping for, but it's what I'm comfortable with in the meantime.

**Comment by murrty** [comment]
After a bit of mulling and ignoring this project, I've decided to keep the feature in. I'm not going to use it myself, but I won't prevent others from using it.
