### ISSUE TITLE
Issue with downloading MSN Video

### ISSUE THREAD

**Issue by gregbtm** [murrty/youtube-dl-gui#119]
An exception occured.

Message: StandardOut has not been redirected or the process hasn't started yet.
Stacktrace:    at System.Diagnostics.Process.BeginOutputReadLine()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass12_0.<BeginDownload>b__0()
Source: System
Target Site: Void BeginOutputReadLine()
Inner Exception: 

========== FULL REPORT ==========
System.InvalidOperationException: StandardOut has not been redirected or the process hasn't started yet.
   at System.Diagnostics.Process.BeginOutputReadLine()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass12_0.<BeginDownload>b__0()
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current version: 2.31-pre1
Curernt culture: English (United Kingdom)
System Caption: Microsoft Windows 11 Pro
Version: 10.0.22621
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by gregbtm** [comment]
I'm trying to download this stream but keep getting the above error -

https://www.msn.com/en-us/video/entertainment/the-75th-annual-tony-awards--mj-performance--cbs/vi-AAYo2cw

**Comment by murrty** [comment]
I can't seem to replicate this at the moment, what fork are you using?

**Comment by murrty** [comment]
Closed due to not being able to replicated, re-open if it has persisted.
