### ISSUE TITLE
Translation key is wrong

### ISSUE THREAD

**Issue by thr3a** [murrty/youtube-dl-gui#120]
The translated keys in English.ini do not seem to match the actual keys.

English.ini: mBatchConverter
Translation keys in the application: mBatchConvert

<img width="316" alt="スクリーンショット 2022-06-18 19 09 01" src="https://user-images.githubusercontent.com/6120301/174433406-428e7e81-e6f0-40d6-8d28-38ca03491371.png">

I changed the translation key "mBatchConverter" to "mBatchConvert" as a test, and the translation was successfully applied.

<img width="253" alt="スクリーンショット 2022-06-18 19 10 02" src="https://user-images.githubusercontent.com/6120301/174433404-216b6cce-4c47-48a0-ba13-af6978b2ce5c.png">

# Version

- 2.31-pre1
- Template version 1.52

**Comment by murrty** [comment]
i'll update the template, keep it as mBatchConvert to keep it in-line with the batch downloader.
