### ISSUE TITLE
unable to update...why...??

### ISSUE THREAD

**Issue by p060477** [murrty/youtube-dl-gui#124]
hi,
i'm getting this error:

Stacktrace:    in System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   in System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   in System.Windows.Forms.Control.Invoke(Delegate method)
   in youtube_dl_gui_updater.frmUpdater.<<SetDownloadThread>b__6_0>d.MoveNext()
Source: System.Windows.Forms
Target Site: System.Object MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
Inner Exception: 

========== FULL REPORT ==========
System.IO.IOException: Impossibile creare un file, se il file esiste già.

   in System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   in System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   in System.Windows.Forms.Control.Invoke(Delegate method)
   in youtube_dl_gui_updater.frmUpdater.<<SetDownloadThread>b__6_0>d.MoveNext()
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current updater version: 1,5
Current culture: Italian (Italy)
OS: Version: 10.0.19043
Service Pack Major: 0
Service Pack Minor: 0
System Caption: Microsoft Windows 10 Home
========== END INFO ==========

**Comment by murrty** [comment]
I should find a way to localize exceptions to English. If the updater is having troubles deleting the youtube-dl-gui.exe file, try doing it manually and updating from there? I'll look into it eventually.

**Comment by p060477** [comment]
hi, yes of course if i delete the folder, i dl the new vers. it works...but i should like to be able to use the update function..
also because when there is a new update a pop up invite me to dl it..but if i choose yes and i click the update choice
 i got this error i have attached...
thxs so much again for yr attention  cheers
