### ISSUE TITLE
Error loading Python DLL

### ISSUE THREAD

**Issue by f242** [murrty/youtube-dl-gui#129]
![image](https://user-images.githubusercontent.com/10371194/188510301-ace51cf9-8ad4-44ac-a9d3-94ab3f0e22f9.png)
https://github.com/murrty/youtube-dl-gui/releases/tag/3.0.0-1 this version

**Comment by murrty** [comment]
Is this a problem on [2.31](https://github.com/murrty/youtube-dl-gui/releases/tag/2.31)?

**Comment by f242** [comment]
> Is this a problem on [2.31](https://github.com/murrty/youtube-dl-gui/releases/tag/2.31)?

2.31 also have problem, i still use 2.0

**Comment by murrty** [comment]
Well it's an issue with yt-dl or python. What does the LoadLibrary error say?

**Comment by f242** [comment]
> Well it's an issue with yt-dl or python. What does the LoadLibrary error say?

the specified module was not found

**Comment by murrty** [comment]
If you are using the standalone .exe and don't have python installed, there might be an issue with your version of youtube-dl, which you can try to update to a newer version, or try using yt-dlp instead as it's preferred over yt-dl.

The only other idea I have is that it might be trying to extract the python library into a protected folder which you don't have access to write to.

**Comment by f242** [comment]
> If you are using the standalone .exe and don't have python installed, there might be an issue with your version of youtube-dl, which you can try to update to a newer version, or try using yt-dlp instead as it's preferred over yt-dl.
it happpens with yt-dlp 2022.9.1.0
> The only other idea I have is that it might be trying to extract the python library into a protected folder which you don't have access to write to.
who trying to extract, yt-dlp or gui?
i use portable mode, .ini was sucessfully saved in this folder

**Comment by murrty** [comment]
youtube-dl extracts the runtime.

Do you have python installed?

**Comment by f242** [comment]
> youtube-dl extracts the runtime.
> 
> Do you have python installed?

no

**Comment by murrty** [comment]
Okay, that might be a requirement for your setup. If you were to download using youtube-dl through the command line, does the issue still occur (without running my program)?

**Comment by f242** [comment]
> Okay, that might be a requirement for your setup. If you were to download using youtube-dl through the command line, does the issue still occur (without running my program)?

i used incorrect version from github, all works fine after replace to right version, sorry
