### ISSUE TITLE
Multiple file download

### ISSUE THREAD

**Issue by DajMiliona** [murrty/youtube-dl-gui#13]
Thx for add quality option select :)
If you can add please suport download multiple files (eample add link to file witch multiple YT urls)

**Comment by murrty** [comment]
I'm working on bulk downloading, but if you have a playlist or even a channel you want to download, just put it in the URL and youtube-dl will handle it.

**Comment by murrty** [comment]
Half a year later, I've added this to 2.2 and there's a beta release ready for it if you want to test it out.
