### ISSUE TITLE
Paste automatically and fixed audio preset

### ISSUE THREAD

**Issue by trimechee** [murrty/youtube-dl-gui#139]
Hello, in order to more speed up the download process especially when you have several videos to download, it will be great that our beloved Youtube-dl-gui automatically detects the urls in the clipboard and analyzes them and starts the download just by clicking on a "paste" button or without the need to click any button, and it will be great to add presets like worst audio quality among youtube dash streams , i.e. a fixed stated preset and Youtube-dl-gui memorizes the last preset used without having to click on the drop-down list and also preset to worst dailymotion video quality so that we can quickly download our favorite show audios, thanks a lot !

**Comment by murrty** [comment]
You mean the "Clipboard auto download" (Tools -> Clipboard auto download) option added in 2.3.1? If you don't have "prefer extended download" enabled in the options, it'll auto-download using the quick downloader with the formats, qualities, etc selected in the main form.

**Comment by trimechee** [comment]
I haven't used Youtube-dl-gui for months, I hesitate to install the Framework 4.7.2 runtime because my pc is old and I would like it to remain fluid fast by avoiding installing software which can weigh it down, windows includes by default net framework 4.8 advanced service; so I'm waiting for your answer if framework 4.8 is enough or should we use Framework 4.7.2? and will the runtime  framework will start at startup and slow down the computer please?

**Comment by murrty** [comment]
I believe the NET Framework 4.8 includes runtimes for 4.7.2, your best bet is to just run it and see.

**Comment by trimechee** [comment]
Great ! thank you so much for your help !
