### ISSUE TITLE
FFmpeg and net framework

### ISSUE THREAD

**Issue by trimechee** [murrty/youtube-dl-gui#140]
Hello, I wonder if we should use the classic FFmpeg or the special version of FFmpeg to avoid bugs? because there is a special builds of FFmpeg for yt-dlp to fix some bugs, it will be great if YouTua can add ann update automatically this special builds of FFmpeg to fix some bugs for example

[Fix AAC HLS streams being truncated mid stream]

[Fix for YouTube's VP9 encodes with non-monotonous DTS]

https://github.com/yt-dlp/FFmpeg-Builds

for net framework, I check the windows features and I see that I have net framework 4.8 advanced service, can we use this version or we must the NET Framework 4.7.2 version?

I'm not sure if I have net framework runtime , I recently updated windows 10 and I'm not sure if windows 10 includes runtime 4.7.2 by default ?

**Comment by murrty** [comment]
You can use either ffmpeg, it doesn't really matter unless the only patch within that build of ffmpeg is important to you. See the other issue about the framework compatibility.

**Comment by trimechee** [comment]
Interesting, thank you for your precious help :)

**Comment by trimechee** [comment]
I decided to donwload this ffmpeg special build, there is 2 versions for windows, ffmpeg-master-latest-win64-gpl-shared.zip 44 mb and ffmpeg-master-latest-win64-gpl.zip 144mb, which one we should download and install please ? and  is  it really necessary to download and instal also ffprobe please ?
  
https://github.com/yt-dlp/FFmpeg-Builds/releases

**Comment by trimechee** [comment]
Sould we put just ffmpeg.exe with Youtube-dl-gui or we should put the whole folder of FFmpeg ?

**Comment by trimechee** [comment]
@murrty After reading, this issue, I'm in the fog and I don't know what exactly to do, which build of ffmpeg is stable or beta please ? and shoud we donwload and isntall the shared build please ? 

https://github.com/yt-dlp/FFmpeg-Builds/issues/10
