### ISSUE TITLE
Audio options

### ISSUE THREAD

**Issue by trimechee** [murrty/youtube-dl-gui#144]
Hello, in audio preset, there is option "worst" and option "VBR" with numbers fromm 0 to 10, please what is the difference about these audio options ? and about "format" in audio section, there is many option "best", "opus", "m4a".....when we wish to download the worst audio quality, which audio we shoud select please ?

**Comment by murrty** [comment]
These are audio formats, if you don't know what that is please look it up because this is for issues relating to the program, not technical write ups as to what audio is.
