### ISSUE TITLE
[Bug] Mysterious folder

### ISSUE THREAD

**Issue by Tox86** [murrty/youtube-dl-gui#15]
Hello i discovered if you change the download folder, the program make a automatic folder called video.

Change the folder:
![Video Folder](https://user-images.githubusercontent.com/7013508/66346586-d3082200-e928-11e9-91b1-b3bd5c9d2f02.gif)

![2019-10-07 17_46_32-Window](https://user-images.githubusercontent.com/7013508/66347332-79a0f280-e92a-11e9-9ff5-961ba5a9c2d8.png)

And go to path:
![d32d](https://user-images.githubusercontent.com/7013508/66347171-1020e400-e92a-11e9-9d39-00ca3e44ee9e.PNG)

Cheers.

**Comment by murrty** [comment]
Uncheck "separate downloads to different folders"

**Comment by Tox86** [comment]
OK sorry
