### ISSUE TITLE
Thumbnails not embedding

### ISSUE THREAD

**Issue by coastercrab** [murrty/youtube-dl-gui#153]
I used to --embed-thumbnail with custom setting to get thumbnails into the video file when I want them.
I just updated to 3.1.1 and now Youtube -dlp throws an error when I try to download any video when I have anything in the custom arguments box (when I have not selected "custom").
If I select custom, it says it's doing all the things to embed the thumbnail, (I even see the image in the folder before it gets deleted) but I'm left with the default one once it's done making the mkv.
I also tried the settings in downloads>general and they made no difference either (but those were ignored before anyway).

EDIT: I reverted to the old version and it still doesn't work.

**Comment by murrty** [comment]
youtube-dl requires atomic parsley (yt-dlp suggesting using [mutagen](https://github.com/quodlibet/mutagen)) to embed thumbnails.
