### ISSUE TITLE
Remember "Close after download"

### ISSUE THREAD

**Issue by githubbapoopa** [murrty/youtube-dl-gui#154]
Nice program!

In daily usage it would be useful (time-saving) if the state of "Close after download" in extended downloads would be remembered. Or if there was an option to set that as default somewhere.

Also column width should be remembered  in that dialogue.

Edit: Columns are ok *if* the main window has a certain size. If size is too small then columns are too small and a change is not remembered (a gui problem I guess).

thx

**Comment by murrty** [comment]
I don't remember if the "Close after download" state is saved in some capacity, but either way i added it to my local repo recently, so it will be available come next version.

Column size saving shouldn't have any problems, but I'll look into it.
