### ISSUE TITLE
Some Characters Can't Be Entered In The Custom Arguments Field

### ISSUE THREAD

**Issue by danepedersen** [murrty/youtube-dl-gui#165]
This issue started with the latest version of youtube-dl-gui (3.2.2.) - it manifests in the form of an error beep whenever a special character like " or / is entered into the custom arguments field.  This issue has never happened before in previous versions (to the best of my knowledge) and is quite frustrating, so a solution would be much appreciated.  Thank you!

**Comment by murrty** [comment]
Oh, you're right, that's not very good. Must have accidentally used the wrong object to suppress.
