### ISSUE TITLE
Narrow UI on Converter tab

### ISSUE THREAD

**Issue by maboroshin** [murrty/youtube-dl-gui#171]
```Video``` and ```Audio``` in the Converter tab have narrow string widths. For Japanese, I would like to see an additional width of 3-4 alphabetical characters.

![image](https://user-images.githubusercontent.com/41102508/215458236-9a69e18f-6824-40c4-b5e2-d5ed610db46f.png)

**Comment by murrty** [comment]
The checkboxes will be on the other side of the text. They'll look uniform and be able to have longer values.

**Comment by maboroshin** [comment]
It fixed on version 3.3.0-1.
![image](https://github.com/murrty/youtube-dl-gui/assets/41102508/8b04b3d4-b2e6-4631-a457-50e6648a3940)
