### ISSUE TITLE
Downloading exactly 2 hours only

### ISSUE THREAD

**Issue by DeffoDan** [murrty/youtube-dl-gui#179]
If ever I put in a URL that contains a video that's more than 2 hours long, the resulting file ends up at a straight 2 hours. I've played around with different settings, and tried various URL's, but I'm trying to downloading something that's nearly 4 hours long. Is there a special command you need to input, or a setting you need to flick on, to download longer streams?

**Comment by qzmtch** [comment]
Hi, ask this question here https://github.com/yt-dlp/yt-dlp/issues
