### ISSUE TITLE
[Bug] Program crashes after startup message

### ISSUE THREAD

**Issue by Splike** [murrty/youtube-dl-gui#18]
I've downloaded the portable version: `youtube-dl-gui.zip` v2.12.

After running `youtube-dl-gui.exe`, i'm shown the following message:

![Screenshot 2020-01-13 21 09 04](https://user-images.githubusercontent.com/7159527/72288520-892a8880-3649-11ea-949e-58d7bf135484.png)

after clicking "Yes", I can see in my task manager, that the program just closes, and nothing else happens.

I have ffmpeg on in my PATH (And for good measure, I tried downloading ffmpeg 4.2.1 x64 static, and placed it besides `youtube-dl-gui-exe`)

I have manually downloaded v2020.01.01 of youtube-dl. both the file `youtube-dl` and `youtube-dl.exe`, just to make sure, as I didn't exactly know which one was the right one.

Also, I have .NET v. 4.8.03752  installed on my machine. Running Windows 10 64-bit v1909

**Comment by murrty** [comment]
see #14
