### ISSUE TITLE
More spaces are needed for Japanese Translation

### ISSUE THREAD

**Issue by tsubasanouta** [murrty/youtube-dl-gui#183]
More spaces are needed in Japanese Translation.
![WS000001](https://user-images.githubusercontent.com/129067724/235921216-04066509-cfaf-43a8-816a-591df2301027.JPG)
![WS000003](https://user-images.githubusercontent.com/129067724/235921245-fe4447de-ada4-4d08-83b9-1f0e2c43a791.jpg)
![WS000002](https://user-images.githubusercontent.com/129067724/235921285-047935fc-742a-4eac-aed7-58adbd8f28f1.JPG)
![WS000004](https://user-images.githubusercontent.com/129067724/235921309-6efb3b88-5d33-40cc-8c5d-7110b866c18e.jpg)

**Comment by murrty** [comment]
v.3.3.0 implements a visual change that should accommodate languages that need more space.

**Comment by maboroshin** [comment]
It fixed. Duplicate: https://github.com/murrty/youtube-dl-gui/issues/171
