### ISSUE TITLE
TenPlay Australia - urlopen EOF Error

### ISSUE THREAD

**Issue by danepedersen** [murrty/youtube-dl-gui#186]
**EDIT: I just experienced the same problem with BBC iPlayer**

Has anyone experienced this error before?  It appears to be an issue with the JSON - here is the verbose output in the download box:

Beginning download, this box will output progress
Using yt-dlp as the download provider.
yt-dlp has been found and set
Generating output directory structure
The output was generated and will be used
Custom was requested, skipping quality + format
The quality and format has been set
Arguments have been generated
Arguments have been generated and are readonly in the textbox
Creating download thread
Created download thread, starting...
Error: [debug] Command-line config: ['https://10play.com.au/inside-moto/episodes/season-1/episode-1/tpv220228djvoi', '-o', 'D:\\[redacted]', '--list-formats', '--verbose', '--cookies', 'D:/10play.com.au_cookies.txt']
Error: [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
Error: [debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
Error: [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
Error: [debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
Error: [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
Error: [debug] Proxy map: {}
Error: [debug] Loaded 1855 extractors
[TenPlay] Extracting URL: https://10play.com.au/inside-moto/episodes/season-1/episode-1/tpv220228djvoi
[TenPlay] tpv220228djvoi: Downloading JSON metadata
Error: ERROR: [TenPlay] tpv220228djvoi: Unable to download JSON metadata: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Error:   File "yt_dlp\extractor\common.py", line 710, in extract
Error:   File "yt_dlp\extractor\tenplay.py", line 85, in _real_extract
Error:   File "yt_dlp\extractor\common.py", line 1064, in download_content
Error:   File "yt_dlp\extractor\common.py", line 1028, in download_handle
Error:   File "yt_dlp\extractor\common.py", line 898, in _download_webpage_handle
Error:   File "yt_dlp\extractor\common.py", line 855, in _request_webpage
Error:   File "urllib\request.py", line 1354, in do_open
Error:   File "http\client.py", line 1252, in request
Error:   File "http\client.py", line 1298, in _send_request
Error:   File "http\client.py", line 1247, in endheaders
Error:   File "http\client.py", line 1007, in _send_output
Error:   File "http\client.py", line 947, in send
Error:   File "http\client.py", line 1421, in connect
Error:   File "ssl.py", line 500, in wrap_socket
Error:   File "ssl.py", line 1040, in _create
Error:   File "ssl.py", line 1309, in do_handshake
Error: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)
Error: During handling of the above exception, another exception occurred:
Error: Traceback (most recent call last):
Error:   File "yt_dlp\extractor\common.py", line 837, in _request_webpage
Error:   File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
Error:   File "urllib\request.py", line 525, in open
Error:   File "urllib\request.py", line 542, in _open
Error:   File "urllib\request.py", line 502, in _call_chain
Error:   File "yt_dlp\utils\_utils.py", line 1514, in https_open
Error:   File "urllib\request.py", line 1357, in do_open
Error: urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
An error occured
THIS IS A YOUTUBE-DL ERROR, NOT A ERROR WITH THIS PROGRAM!

**Comment by murrty** [comment]
This is an error with yt-dlp, I can't really help with this.

**Comment by danepedersen** [comment]
Ah, I will flag it on their Github then.  Thanks for letting me know and my apologies for posting it to the wrong forum.
