### ISSUE TITLE
 New error failed v3.2.3

### ISSUE THREAD

**Issue by Lighthouselp95** [murrty/youtube-dl-gui#188]
Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
An error occured
THIS IS A YOUTUBE-DL ERROR, NOT A ERROR WITH THIS PROGRAM!

**Comment by murrty** [comment]
This is a yt-dlp error, you might need to run with "--verbose" argument and give them the error in their repo.
