### ISSUE TITLE
how to use -f worstvideo+worstaudio for youtube-dl-gui?

### ISSUE THREAD

**Issue by candrapersada** [murrty/youtube-dl-gui#19]
how to use youtube-dl -f worstvideo+worstaudio in custom arguments youtube-dl-gui?

**Comment by murrty** [comment]
check "Custom" under Download type and then input the arguments above the download button.

**Comment by candrapersada** [comment]
but how to use format video and audio use -f worstvideo+worstaudio?

**Comment by murrty** [comment]
Do them one at a time
