### ISSUE TITLE
Sorry but

### ISSUE THREAD

**Issue by Tox86** [murrty/youtube-dl-gui#2]
Another bug sorry :
![error](https://user-images.githubusercontent.com/7013508/36629894-9f775fdc-193b-11e8-8b09-f05c2fda6cc1.PNG)

**Comment by murrty** [comment]
Double check that youtube-dl.exe exists in the folder you stored it in. There was a bug where changing the settings would include extra youtube-dl.exe in place so I fixed that. Get the latest version.

**Comment by Tox86** [comment]
I can't open and go automatic to the hidden icons (Sorry for my bad English).
Version 1.65:

https://imgur.com/LdoFFII

.NET Error
![net](https://user-images.githubusercontent.com/7013508/36642587-3c101a02-1a20-11e8-8abb-b5aa4ecb27a8.gif)

**Comment by Nuke142** [comment]
How to merge video and audio file in two one?
I see Convert tab fully useless. Is it only for reconvert not for merge?

**Comment by Tox86** [comment]
Nope :(
![error](https://user-images.githubusercontent.com/7013508/36690294-a12638b8-1b10-11e8-8692-d738eb976e51.gif)
