### ISSUE TITLE
Version 2.2 - GUI fixes request 

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#25]
@murrty 

Please enlarge width of "Main" and "Settings" windows.
Some strings not have enough space for not English language.

Please check the screens

![Youtube-DL-GUI-2 2-01](https://user-images.githubusercontent.com/1262554/75437321-52d56e00-5956-11ea-992d-60c23763208a.jpg)

![Youtube-DL-GUI-2 2-02](https://user-images.githubusercontent.com/1262554/75437333-57018b80-5956-11ea-8fb0-7a81011ae434.jpg)

![Youtube-DL-GUI-2 2-03](https://user-images.githubusercontent.com/1262554/75437351-5b2da900-5956-11ea-9c1e-aeffbcd3bab1.jpg)

![Youtube-DL-GUI-2 2-04](https://user-images.githubusercontent.com/1262554/75437362-5ff25d00-5956-11ea-9d7d-13f83de99ec7.jpg)

![Youtube-DL-GUI-2 2-05](https://user-images.githubusercontent.com/1262554/75437369-641e7a80-5956-11ea-9eb3-d5ffcc3e1702.jpg)

![Youtube-DL-GUI-2 2-06](https://user-images.githubusercontent.com/1262554/75437381-684a9800-5956-11ea-8148-a6e6c4f785f4.jpg)

![Youtube-DL-GUI-2 2-07](https://user-images.githubusercontent.com/1262554/75437400-6da7e280-5956-11ea-8369-5d5a4bfa85f4.jpg)

I already create a PR for Italian language.
Pelase merge it before to fix the GUI.

**Comment by murrty** [comment]
Hey there, some of the non-translated languages are hard-coded into the application right now. I do plan on making more of the application more translatable, but translating it as its base was pretty overwhelming so I'm gonna sit on the untranslated parts for a short while.

As for the some of the uneven controls, check the latest release (v2.21) as I fixed some of them in there, and I will release more fixes to address other uneven or weird-looking controls. I can address them in code now, but I can't release a new update at this moment.

**Comment by bovirus** [comment]
Version 2.2.1 not include Italian.

**Comment by murrty** [comment]
Not yet, it'll be included in the next update, but it's available to be manually downloaded from the repo at any time. I'm working on fixing visual problems, and some are already fixed in source.

**Comment by bovirus** [comment]
OK!
I will wait for new releases then I will update my feedback about it.
Please don't close this issue until you will fixed them as much as possible.
