### ISSUE TITLE
Version 2.21 - Error

### ISSUE THREAD

**Issue by smaragdus** [murrty/youtube-dl-gui#27]
While using [youtube-dl-gui](https://github.com/murrty/youtube-dl-gui) with an older version of [youtube-dl](https://github.com/ytdl-org/youtube-dl)- [2020.01.24](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.01.24) I got the following error message:

```
Feel free to copy + paste this entire text wall into a new issue on Github

Version: 2.21
Reported Exception: An exception occured
Message: The system cannot find the file specified
Stacktrace:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass9.<BeginDownload>b__4()
Source: System
TargetSite: Boolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
Full report:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass9.<BeginDownload>b__4()
```

**screen:**

![youtube-dl-gui 2 21 - 2020-02-28 - error - 001](https://user-images.githubusercontent.com/9025757/75504567-7d203d80-59e1-11ea-9daa-5d69cd266027.png)

When I updated [youtube-dl-gui](https://github.com/murrty/youtube-dl-gui) to the latest version- [2020.02.16](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.02.16), I didn't get this error any more. Yet I decided to report the problem as it might provide some useful information for you.

I am using **youtube-dl-gui** on Windows 8 x64.

**Comment by murrty** [comment]
Did the youtube-dl you use before be named "youtube-dl.exe" exactly? This doesn't account for executables with different names, and it looks like it didn't exist wherever you had it.

**Comment by smaragdus** [comment]
@murrty 

> Did the youtube-dl you use before be named "youtube-dl.exe" exactly? This doesn't account for executables with different names, and it looks like it didn't exist wherever you had it.

Yes, the name was youtube-dl.exe which I downloaded from [releases](https://github.com/ytdl-org/youtube-dl/releases). But I think that first time when I started the executable (youtube-dl-gui.exe) I had forgotten to put youtube-dl.exe in the program folder. Later I put it there but perhaps the configuration file (user.config) was not updated.

Now I tried to recreate the condition and I succeeded to reproduce the error:

1. start youtube-dl-gui without youtube-dl.exe present in program folder;
2. try to download a video;
3. put youtube-dl.exe in program folder later;
4. error message appears;
5. exit youtube-dl-gui;
6. restart youtube-dl-gui;
7. the error message no longer appears;

So after I  put youtube-dl.exe in program folder I need to restart youtube-dl-gui and the problem is resolved. So I am closing this issue.

**Comment by murrty** [comment]
I probably fixed it. I know it stems from not re-scanning every download, because that's a lot of overhead, and I figured I'd remove a verification method because it wasn't very stable, and redundant at best. It'll re-scan every time it tries to download but couldn't find youtube-dl, that's a fair middle-ground.
