### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by iowbeoibewio** [murrty/youtube-dl-gui#29]
Hi, I tried to use convert tab and after choose file (was MP4) and choose both input and output then I click convert button i get this error, I tried to change output format and same error

using windows 10 with latest .NET Framework version and youtube-dl-gui 2.21

thank you

```
Feel free to copy + paste this entire text wall into a new issue on Github

Version: 2.21
Reported Exception: An exception occured
Message: The system cannot find the file specified
Stacktrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType)
Source: System
TargetSite: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
Full report:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType)
```

**Comment by murrty** [comment]
Do you have ffmpeg?

**Comment by iowbeoibewio** [comment]
I think it's included with media pack I already installed it on my PC

**Comment by murrty** [comment]
if you type "ffmpeg" into a command prompt window, does it say "ffmpeg is not recognized as an internal or external command"?

**Comment by iowbeoibewio** [comment]
I fix it by putting ffmpeg.exe - ffplay.exe - ffprobe.exe together with youtube-dl-gui.exe

working 100%

thanks
