### ISSUE TITLE
Merge video and audio?

### ISSUE THREAD

**Issue by Nuke142** [murrty/youtube-dl-gui#3]
How to merge video and audio file in two one?
I see Convert tab fully useless. Is it only for reconvert not for merge?

**Comment by Tox86** [comment]
ffmpeg into your youtube-dl gui folder.

![ffmpeg](https://user-images.githubusercontent.com/7013508/36677657-850ded4c-1aed-11e8-948a-dc8c754c7c60.PNG)

**Comment by Masutin** [comment]
Merge with:
ffmpeg -i "%~1" -i "%~2" -codec copy "%~3"
if errorlevel 1 exit 1
del "%~1" "%~2"

**Comment by murrty** [comment]
Hey there,

Hopefully this feature isn't passed due, I added it to [v2.12](https://github.com/murrty/youtube-dl-gui/releases/tag/2.12). It's been over a year, but I wanted to research into it before committing it.

Either way, it's a feature now.
