### ISSUE TITLE
Error on download youtube-dl

### ISSUE THREAD

**Issue by xetrin** [murrty/youtube-dl-gui#32]
A WebException occured at https://github.com/ytdl-org/youtube-dl/releases/download/2020.03.24/youtube-dl.exe

Unknown error
An exception of unknown type has occurred.System.ArgumentException: Пустое имя пути не допускается.
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   в System.Net.WebClient.DownloadFile(Uri address, String fileName)

StackTrace:
   в System.Net.WebClient.DownloadFile(Uri address, String fileName)
   в System.Net.WebClient.DownloadFile(String address, String fileName)
   в youtube_dl_gui.UpdateChecker.<UpdateYoutubeDl>b__4()

**Comment by murrty** [comment]
This issue has been fixed, but Github won't actually post the files, so it's staying open until Github works.

**Comment by candrapersada** [comment]
how to update version YouTube-dl from YouTube-DL-GUI?
