### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by xetrin** [murrty/youtube-dl-gui#33]
[Russian.ini](https://download1483.mediafire.com/zkfnxopgfnfg/9aegaq0tnpy404u/Russian.ini)

**Comment by murrty** [comment]
Hey,  I appreciate the translations, but can you fork the project and edit the Russian language file? It's easier to manage than uploading it off somewhere else.

**Comment by xetrin** [comment]
Hello! I'll try. Git has never dealt with.
