### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by XanGregor** [murrty/youtube-dl-gui#34]
[Spanish.zip](https://github.com/murrty/youtube-dl-gui/files/4537539/Spanish.zip)

**Comment by murrty** [comment]
Hey, I appreciate the translations, but can you fork the project, create the language file and make a pull request? You'll get tagged as a collaborator on the project.

**Comment by XanGregor** [comment]
I'm not very familiar with Git, but i'll try. If it doesn't work, nevermind the tag, I just wanted to contribute to the project, because I use it very often.
