### ISSUE TITLE
how to edit youtube playlist?

### ISSUE THREAD

**Issue by candrapersada** [murrty/youtube-dl-gui#35]
how to edit youtube playlist?
![Capture](https://user-images.githubusercontent.com/36833664/80674054-097ed780-8adb-11ea-9f79-b88a673bd248.PNG)

**Comment by murrty** [comment]
What do you mean? Just edit the playlist on youtube. This also doesn't resemble any part of my actively released program, unless I forgot I added something a long time ago.

**Comment by candrapersada** [comment]
I have a video playlist URL having 128 items and I have already downloaded 25 videos from same playlist URL. Now I want to download remaining videos starting from 26 index But I am not able to download it using start option.

**Comment by murrty** [comment]
Well, if they already exist (with the proper names), then they will not be downloaded. You can just download using the playlist URL and it should continue from 26.
