### ISSUE TITLE
aac instead of opus

### ISSUE THREAD

**Issue by RomanVanish** [murrty/youtube-dl-gui#41]
Why 2.23 saves audio in aac, while its original extenstion (as it is in original video file) is opus.
I compared it with 2.22 version.. So it does it in original opus...

**Comment by murrty** [comment]
What quality are you downloading with on both versions?

**Comment by RomanVanish** [comment]
same options, same video sample, "best" on both versions and "no vbr"

"I think it might have been a bug that I just fixed in commit 4dc30c6 depending on the circumstance."
Is it already available for download?

**Comment by RomanVanish** [comment]
Yes, it helps, ty.
