### ISSUE TITLE
Can't remember FFMPEG location

### ISSUE THREAD

**Issue by everythingisonfireagain** [murrty/youtube-dl-gui#42]
Anytime I try to set the folder where ffmpeg and ffprobe are located, it just clears them whenever I exit the settings window, even when I click save prior. It stays when I click Use static ffmpeg, but when I try to convert a file it just says it's null as if it hadn't anyway. From downloading, it's just a regular "ERROR: ffmpeg or avconv not found. Please install one." message Here's the log from converting

Version: 2.23
Reported Exception: An exception occured
Message: FFmpegPath is null. Cannot convert. If you do not have ffmpeg, consider downloading it.
Stacktrace:    at youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType)
Source: youtube-dl-gui
TargetSite: Boolean convertFile(System.String, System.String, Int32)
Full report:
System.Exception: FFmpegPath is null. Cannot convert. If you do not have ffmpeg, consider downloading it.
   at youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType

**Comment by Acciprovus** [comment]
I'm having the same issue. I have tried everything but reverting back to an older version.

**Comment by everythingisonfireagain** [comment]
It doesn't change anything when the program is restarted (using newest released version 2.24)

**Comment by murrty** [comment]
Try downloading again, and send the text in the second textbox which should contain arguments that are being passed. I can't seem to reproduce the issue.

**Comment by everythingisonfireagain** [comment]
https://www.youtube.com/watch?v=4br95yWLE2U -o "C:\Users\Patty\Downloads\youtube.com\Video\%(title)s-%(id)s-%(timestamp)s-%(upload_date).%(ext)s" -f "bestvideo+bestaudio/best[ext=mp4]/best" --write-info-json --add-metadata

**Comment by murrty** [comment]
[try this build](https://github.com/murrty/youtube-dl-gui/files/4807031/youtube-dl-gui.zip).

**Comment by everythingisonfireagain** [comment]
I tried it with the build provided and it didn't make any difference. However, on a hunch, I moved the build along with ytdl & ffmpeg to a different drive - my System OS on C: as opposed to my other internal hard drive on D: - and it solved it! It solves it for the stable release as well.

**Comment by murrty** [comment]
I guess this is solved, then.
