### ISSUE TITLE
[BUG] Batch processing does not embed thumbnails into file

### ISSUE THREAD

**Issue by Cj5VdMzj0B** [murrty/youtube-dl-gui#46]
During batch processing, the thumbnails are not embedded in the file.

**Comment by murrty** [comment]
That doesn't seem right. The files need to be MP4 to properly embed, so that might be the issue.

I can't really do much more than that without more information, like output logs and the generated arguments.

**Comment by murrty** [comment]
If you still have this issue, create a new one with more information.
