### ISSUE TITLE
Youtube-dl.exe close alone

### ISSUE THREAD

**Issue by Tox86** [murrty/youtube-dl-gui#5]
Hello, i think this is a new bug on the youtube-dl-gui.

youtube-dl version: Lasted.

https://imgur.com/a/swArCp0

Cheers.

**Comment by murrty** [comment]
Current version does not include the save directory, so using the custom arguments current requires you to pass them as well.

it's already fixed in a [pre-release](https://github.com/murrty/youtube-dl-gui/releases/tag/2.0_debug-2019-05-25).
