### ISSUE TITLE
Suggestion:  Add Beatstars.com 

### ISSUE THREAD

**Issue by woodgrain816** [murrty/youtube-dl-gui#51]
Is there anyway to add support for BeatStars.com? e.g. https://www.beatstars.com/beat/circumstances-4282656 and/or https://bsta.rs/6cfb3f59
P.S. Is there anyway to donate to this project?

**Comment by murrty** [comment]
Well, this program doesn't handle any actual downloading. It's essentially a front-end for the command line tool. I can't inherently add support for non-supported websites. You can ask on the [youtube-dl github](https://github.com/ytdl-org/youtube-dl/issues/new?labels=site-support-request&template=2_site_support_request.md&title=).

To answer your donate question, not this program. youtube-dl used to have a way to donate, but I don't know if they removed it or not.
