### ISSUE TITLE
youtube-dl-gui 2.25 - Don't save language settings

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#54]
@murrty 

Seems that youtube 2.25 don't save language settings.

Run program.
Setup Italian language and Save.
Close program
Start program again but Start in English. Not in Italian.

**Comment by murrty** [comment]
I'm not able to reproduce this issue. Double check your language file and try again?

**Comment by bovirus** [comment]
@murrty

It's a quite strange bug.
I decomrpess the fiels in anotehr directory and it worked.
In first directory content the .ini file don't save Italin language settings.
Strange.
