### ISSUE TITLE
Problem with Version 2.51 - does crash constantly

### ISSUE THREAD

**Issue by Olaf15** [murrty/youtube-dl-gui#57]
Version: 2,251
Reported Exception: An exception occured
Message: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Stacktrace:    bei youtube_dl_gui.frmDownloader.CloseForm()
Source: youtube-dl-gui
TargetSite: Void CloseForm()
Full report:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

**Comment by murrty** [comment]
Does it happen if the download is finished?
Does it happen during the download?
Does it happen before the download?
