### ISSUE TITLE
add youtube-dlc

### ISSUE THREAD

**Issue by candrapersada** [murrty/youtube-dl-gui#61]
Youtube-dl has been heavily [uncommitted for the past few month](https://github.com/ytdl-org/youtube-dl/graphs/commit-activity)s, and there's been a [new fork](https://github.com/blackjack4494/yt-dlc/releases) that's kind-of taken on the reigns. Wondering if it would be possible to perhaps give the option of supporting that instead of the original one?

**Comment by murrty** [comment]
I can add it as an option in a future version.

**Comment by Dr-Flay** [comment]
13 commits on Monday. Will that do ?
https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by murrty** [comment]
Now that youtube-dl was reinstated, I don't think this will be needed.
