### ISSUE TITLE
Does not save download location

### ISSUE THREAD

**Issue by rain1598** [murrty/youtube-dl-gui#67]
I tried to save the download location to somewhere other than my downloads folder, but it always resets
I also tried to edit the downloadPath and FirstTime in settings.ini but it still resets to default
I am using windows 10 with .NET v4.8.04084

**Comment by itzikvil** [comment]
same to me,

i open program->settings->download path-> and insert path then press save, i can see the the path is saved within settings.ini under the [Download] section e.g downloadPath= is as i wanted though when i close and open the program i keep getting the message for configuring the path and it happens every time i reopen the program (as oppose to leaving it minimized then and not closing it) if i press no on that message and not configuring the download path then it defaults to c:\users\USER\... and the other option is to choose the path again and again (it does not save it) and its frustrating... i am in itzikv@gmail.com hope this is not a major issue and can be fixed.

thanks a lot for what you are doing.

**Comment by murrty** [comment]
Question: did you run the program for the first time with a "settings.ini" file already present? if you haven't, did you move the application to a new folder with the "settings.ini" file and run it again?

i think it might have been an issue regarding the ini file saving the FirstTime setting properly, but it's not being checked through the ini, it's being checked through the file in the local appdata folder.

Can you try again using [the pre-release](https://github.com/murrty/youtube-dl-gui/releases/tag/2.26-pre1) for the next version?

**Comment by itzikvil** [comment]
Hi murrty,

first i would like to thank you for getting back to me so fast and doing great work with this software 👍 and i would like to tell you that now its ok, i have found the problem, when you edit settings.ini you need to change
[youtube-dl-gui]
FirstTime=False
once doing that all sorted out, it seems lie when FirstTime=True initiated it tied up with the Download location message and once  changed it no message appears and its ok.

happy to help and thanks keep up good work

itzik

**Comment by Jules-A** [comment]
Ah, I can confirm with itzikvil, the latest version doesn't update the FirstTime variable in settings.ini and changing it manually will stop it asking. I tried deleting the config files in appdata but that didn't seem to help.

**Comment by murrty** [comment]
hey there, i updated the pre-release, so try it out and see if it fixes your problems (if you still have it)

**Comment by Jules-A** [comment]
> hey there, i released another pre-release, so try it out and see if it fixes your problems (if you still have it)
It fixed the regression introduced by the first pre-release version but I didn't experience the issues the other guys were having in previous versions.

**Comment by rain1598** [comment]
I checked out the new pre-release and it works, thanks for fixing it!
