### ISSUE TITLE
Message: FFmpegPath is null

### ISSUE THREAD

**Issue by Trollheimer** [murrty/youtube-dl-gui#68]
Hello world, please help me.
I get the message:
Version: 2,252
Reported Exception: An exception occured
Message: FFmpegPath is null. Cannot convert. If you do not have ffmpeg, consider downloading it.
Stacktrace:    bei youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType)
Source: youtube-dl-gui
TargetSite: Boolean convertFile(System.String, System.String, Int32)
Full report:
System.Exception: FFmpegPath is null. Cannot convert. If you do not have ffmpeg, consider downloading it.
   bei youtube_dl_gui.Convert.convertFile(String input, String output, Int32 convType)
   
  But in the general settings, I saved the ffmpeg directory.
  
  My sttings.ini:
  [youtube-dl-gui]
FirstTime=True
[Downloads]
downloadPath=F:\
separateDownloads=True
SaveFormatQuality=True
deleteYtdlOnClose=False
useYtdlUpdater=True
fileNameSchema=%(title)s-%(id)s.%(ext)s
fixReddit=True
separateIntoWebsiteURL=True
SaveSubtitles=False
subtitlesLanguages=en
CloseDownloaderAfterFinish=True
UseProxy=False
ProxyType=-1
ProxyIP=
ProxyPort=
SaveThumbnail=False
SaveDescription=False
SaveVideoInfo=False
SaveAnnotations=False
SubtitleFormat=
DownloadLimit=0
RetryAttempts=10
DownloadLimitType=1
ForceIPv4=False
ForceIPv6=False
LimitDownloads=False
EmbedSubtitles=False
EmbedThumbnails=False
VideoDownloadSound=True
AudioDownloadAsVBR=False
KeepOriginalFiles=False
WriteMetadata=False
SkipBatchTip=False
AutomaticallyDownloadFromProtocol=True
[Batch]
SelectedType=-1
SelectedVideoQuality=0
SelectedVideoFormat=0
SelectedAudioQuality=0
SelectedAudioFormat=0
DownloadVideoSound=False
DownloadAudioVBR=False
SelectedAudioQualityVBR=0
CustomArguments=
[Converts]
detectFiletype=True
clearOutput=False
clearInput=False
videoBitrate=7500
videoPreset=5
videoProfile=1
videoCRF=8
videoFastStart=False
hideFFmpegCompile=False
audioBitrate=256
videoUseBitrate=False
videoUsePreset=False
videoUseProfile=False
videoUseCRF=True
audioUseBitrate=True
[Errors]
detailedErrors=False
logErrors=False
suppressErrors=False
[General]
UseStaticYtdl=False
ytdlPath=
UseStaticFFmpeg=True
ffmpegPath=F:\youtube\ffmpeg\bin
CheckForUpdatesOnLaunch=False
HoverOverURLTextBoxToPaste=True
ClearURLOnDownload=False
SaveCustomArgs=2
ClearClipboardOnDownload=False
[Saved]
downloadType=0
downloadArgs=
formTrue0=False
convertSaveVideoIndex=0
convertSaveAudioIndex=1
convertType=1
convertCustom=
videoQuality=0
audioQuality=0
VideoFormat=0
AudioFormat=0
AudioVBRQuality=0
BatchFormX=-999999
BatchFormY=-999999
MainFormSize=268,360
SettingsFormSize=344,425
[Settings]
extensionsName=
extensionsShort=
LanguageFile=

Thanks a lot for helping....

**Comment by lazka** [comment]
same here

**Comment by lazka** [comment]
Moving ffmpeg.exe to the same directory as youtube-dl-gui.exe fixes things

**Comment by Trollheimer** [comment]
Thanks very much! This is the solution!!!

**Comment by murrty** [comment]
I don't know if anyone still runs into this issue, but I fixed a lot of verification. It's probably easier to drop it into the same folder, but I can't replicate the error. If you still have this issue with the latest version (2.26), open a new issue.
