### ISSUE TITLE
Add option to change the batch download path

### ISSUE THREAD

**Issue by Juliana1989** [murrty/youtube-dl-gui#71]
Hello, i would like to change the batch download path (i use custom video with add header x-li-identity) - youtube-dl-gui adds all the time "# Batch Downloads #/timestamp/" to my -o path. its annoying i saw this in your file:

Forms/frmBatchDownloader.cs

                string BatchTime = "\\# Batch Downloads #" + BatchDownloader.CurrentTime()
in Line 292

could you add an option to ignore this or at least to change this? thank you very much. 

a happy new year!

**Comment by murrty** [comment]
i added this as an option, which will come out next update. eventually.
