### ISSUE TITLE
Drop down menu for multiple custom arguments [enhancement]

### ISSUE THREAD

**Issue by plissken1138** [murrty/youtube-dl-gui#73]
If it's possible, a drop down menu for several different custom argument, could be for each new entered to be automatically saved or an option to enter predetermined custom arguments to be shown in such drop down menu.

**Comment by murrty** [comment]
In the latest pre-release, I added a history for file schema. Is that something that would be nice to have for the custom arguments? They wouldn't be per-website, though.

**Comment by plissken1138** [comment]
yeah, something like that, not per-site of course, but shall we say a history of 5-10 options. often I'd like to download certain combinations of dash streams and mux them into some container, with or without subs, so having those commands ready would be very handy.

**Comment by Jules-A** [comment]
It would be a start, preferably I'd prefer argument profiles with the ability to name them. Having the ability to automatically select a profile depending on the website would be awesome but maybe a little difficult to do.

**Comment by murrty** [comment]
Added argument saving with 2.26, I'm not sure how I can do site-based arguments efficiently yet, but I won't count it out.
