### ISSUE TITLE
Problem delete metadata

### ISSUE THREAD

**Issue by KERNEL59** [murrty/youtube-dl-gui#75]
Hi , 

with cmd i use line : youtube-dl -o %(title)s.%(ext)s -f bestaudio --extract-audio --audio-format mp3 --audio-quality 320 **no-info=1**

with youtube-dl Gui , i use **custom arguments** result : 

> ERROR: 'no-info=1' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:no-info=1" ) to search YouTube An error occured

i search keyword for delete metadata please , thanx in advance :)

**Comment by murrty** [comment]
Where are you getting "no-info=1" from? That's not a valid youtube-dl command, and it doesn't download metadata by default.
