### ISSUE TITLE
[Bug]? Infinity loop on settings

### ISSUE THREAD

**Issue by flopezre** [murrty/youtube-dl-gui#76]
Hello, well that is my problem:

![loop_bug](https://user-images.githubusercontent.com/4932575/107286846-e3aa3a00-6a3f-11eb-9b46-45902f0a6632.gif)

?????
Cheers..

**Comment by Jules-A** [comment]
Fixed in pre-release build: https://github.com/murrty/youtube-dl-gui/releases/tag/2.26-pre2 
Not sure why it wasn't just released as a release version to fix a major bug though.

**Comment by murrty** [comment]
since it's already fixed, closing.
