### ISSUE TITLE
urlopen error [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by woodgrain816** [murrty/youtube-dl-gui#78]
Tried to download this: https://youtu.be/UojkOsOqI_c

Creating download thread
Created, starting download thread
[youtube] UojkOsOqI_c: Downloading webpage
[youtube] UojkOsOqI_c: Downloading MPD manifest
Error:
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>

An error occured

**Comment by murrty** [comment]
this is a problem with youtube-dl
