### ISSUE TITLE
Translation setting is sometimes ignored

### ISSUE THREAD

**Issue by PeterNerlich** [murrty/youtube-dl-gui#84]
I have been trying this on Windows 10 today. I observed the language setting not persisting over multiple program starts. Later it worked. Then it didn't anymore. I am sorry, this might be one of the nightmare type bugs to chase around.

I can confirm that the settings file properly reflects the last selected option even if the next program start used English again. Opening the language settings and clicking save removed that line (or just the value, maybe even both at different times, so I naively think there could be duplicated code handling this where the one works, the other doesn't...?), selecting German correctly set that value again.

**Comment by murrty** [comment]
i sometimes fear this code base is possessed

**Comment by murrty** [comment]
Hey, it's been a minute.

Can you confirm if this problem still occurs? hopefully it got fixed on some off-chance and i can pretend i know exactly how i did fix it.

**Comment by murrty** [comment]
Since there's no update on whether this is still happening, I'm going to close it. Create a new issue if it continues to happen.
