### ISSUE TITLE
downloading... and on

### ISSUE THREAD

**Issue by repath** [murrty/youtube-dl-gui#85]
Feel free to copy + paste this entire text wall into a new issue on Github
Dear team,  first of all, thank you for being gracious for the support., God Bless You All..

Version: 2.252
Reported Exception: An exception occured
Message: Object reference not set to an instance of an object.
Stacktrace:    at youtube_dl_gui.frmDownloader.CloseForm()
Source: youtube-dl-gui
TargetSite: Void CloseForm()
Full report:
System.NullReferenceException: Object reference not set to an instance of an object.
   at youtube_dl_gui.frmDownloader.CloseForm()

**Comment by murrty** [comment]
I'm pretty sure i already fixed this in a previous commit. If you get this error repeatedly, try downloading the latest pre-release and see if it is resolved.
