### ISSUE TITLE
Interface - Strings not translated / GUI improvements

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#87]
@murrty 

Please check screenshots for strings untranslated

![image](https://user-images.githubusercontent.com/1262554/113694802-80035c80-96d0-11eb-8c29-c9ee6a738f9a.png)

![image](https://user-images.githubusercontent.com/1262554/113694848-8b568800-96d0-11eb-9a40-68d4566128f3.png)

![image](https://user-images.githubusercontent.com/1262554/113694877-91e4ff80-96d0-11eb-9f34-8ba8b7de71ef.png)

If you can please add to the language file

![image](https://user-images.githubusercontent.com/1262554/113695161-da042200-96d0-11eb-99aa-37dfba18c0c7.png)

Increase window width to have strings longer

![image](https://user-images.githubusercontent.com/1262554/113695240-f2743c80-96d0-11eb-9515-4438cb74611e.png)

Increase space wdth for strings

Thanks.

**Comment by murrty** [comment]
I did most of these, the last one i'm probably just going to leave it as is for now, until i can find a better suit for position calculation.
