### ISSUE TITLE
No error.log

### ISSUE THREAD

**Issue by holyeff** [murrty/youtube-dl-gui#9]
I tried adding a custom paramater, this one:
-f "bestvideo[height<=480]+bestaudio/best[height<=480]" 

I get an error in the command window but the window closes immediately so I can't read what it is. Also,  I checked Save errors as error.log in Settings but no error.log is created.

**Comment by murrty** [comment]
Errors from youtube-dl don't get saved as a error.log, i was planning on implementing a outputredirection but i haven't found a comfortable way of making it work that wouldn't be intrusive.
