### ISSUE TITLE
v2.26 failing to download videos

### ISSUE THREAD

**Issue by Hew-ux** [murrty/youtube-dl-gui#93]
Updated from the previous version to v2.26. Now, any video download is immediately met with:

```
Error:
ERROR: requested format not available

An error occured
THIS IS A YOUTUBE-DL ERROR, NOT A ERROR WITH THIS PROGRAM!
```

This happens with all videos, with all formats, even ones that were working previously. Using youtube-dl via command line works just fine.

Turned on update-checking, opened the program again to test one last time and this appeared:
```
rtbExceptionDetails

Version: 2.26
An exception occured
Message: Input string was not in a correct format.
Stacktrace:    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at youtube_dl_gui.GitData.GitLinks.GetGitVersionDecimal(String InputVersion)
   at youtube_dl_gui.UpdateChecker.GetGitVersion(Int32 GitID)
Source: mscorlib
Target Site: Void StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
Full report:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at youtube_dl_gui.GitData.GitLinks.GetGitVersionDecimal(String InputVersion)
```
so it seems like some formatting is being lost when youtube-dl-gui is sending out commands to the command line?

**Comment by murrty** [comment]
can you give me the link you're trying to download?

**Comment by robin100r** [comment]
Hello,

Here is a link : after to have tried to change the settings" i get the video but never the sound
https://hssodcplus-s.akamaihd.net/ondemand/playready/canalplus/d17/d17_1174926_9_D17/936997/d17-1174926-9-D17.ism/manifest

**Comment by Hew-ux** [comment]
It occurs with every video, but here's a specific one https://m.youtube.com/watch?v=ypVhPbYIUA4

**Comment by murrty** [comment]
sorry, i'm still not able to replicate this. can you send me your settings.ini file (if you use it), or enable it in the settings and send it?

**Comment by Hew-ux** [comment]
Interesting development, I think I found the issue. When starting youtube-dl-gui by navigating to the folder and double clicking it, everything works fine. But if I start it using a shortcut, the aforementioned happens. I have confirmed that this only occurs with v2.26 and not v2.25. I've attached both the settings.ini and the shortcut (you can also generate a shortcut with the rught click menu in case your paths are different).
[All.zip](https://github.com/murrty/youtube-dl-gui/files/6937220/All.zip)

Is there a way to start youtube-dl-gui in debug mode so it's possible to see the exact command that gets sent down the pipeline? I think that the one in the gui isn't accurate (when this issue is occurring).

**Comment by murrty** [comment]
I'll take a look, I started to shift away from "Environment.CurrentDirectory" because of the chance it might be different if ran through a command line, that's probably the cause.

I'll take a look at this, in the meantime, can you test this version and see if it works different? The only difference between this build and current released is https://github.com/murrty/youtube-dl-gui/blob/497f8384d07f3e3f8ba470a1cac6f6823410271f/Program.cs#L11 is changed to ```public static volatile string ProgramPath = Environment.CurrentDirectory;```
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/6940142/youtube-dl-gui.zip)

**Comment by Hew-ux** [comment]
That version seems to work fine.

I went back and tried the v2.26 version again, the one with the issue, now the update check string error comes up no matter if it's launched from shortcut or no. But, for some reason now it can download videos again. I noticed it went back to the default path, though, so I set it back to my custom path and it was still working. Maybe this is an issue that solely occurs to people updating from the old settings format to the new one?

The weird thing is when I initially updated the program it took the liberty of resetting all my settings anyway.

**Comment by murrty** [comment]
There's not really much of a new format, as opposed to changing how it's handled internally. I don't think I would have expected it to replace settings, but considering it checked for the ini file before instead of a "useIni" setting in the ini file, I think it would be side effect.

I'm not sure if this is considered fixed, now.

**Comment by Hew-ux** [comment]
Well we know the cause of the issue is that `System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location()` fails while `Environment.CurrentDirectory` doesn't, but as you said you couldn't replicate the issue on your setup. I wouldn't want to hold back the code of the gui just for my machine to work with it but I'm just afraid that others are experiencing too. If it does occur again then it's worth further investigation but as of right now I'm happy to close this issue.
