### ISSUE TITLE
2.26 updating yt-dlp issue

### ISSUE THREAD

**Issue by plissken1138** [murrty/youtube-dl-gui#95]
Looks like it only attempts auto-update of (now pretty much obsolete) youtube-dl, even if yt-dlp fork is sellected.
If "check for update on launch" is activated, this pops up each time.

>rtbExceptionDetails
>
>Version: 2.26
>An exception occured
>Message: Index was outside the bounds of the array.
>Stacktrace:    at youtube_dl_gui.UpdateChecker.GetYoutubeDlVersion(Int32 GitID)
>Source: youtube-dl-gui
>Target Site: System.String GetYoutubeDlVersion(Int32)
>Full report:
>System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at youtube_dl_gui.UpdateChecker.GetYoutubeDlVersion(Int32 GitID)

Following two warnings pop up when "re-download youtube-dl" is clicked i(yt-dlp fork is sellected):

>rtbExceptionDetails
>
>Version: 2.26
>An exception occured
>Message: Index was outside the bounds of the array.
>Stacktrace:    at youtube_dl_gui.UpdateChecker.GetYoutubeDlVersion(Int32 GitID)
>Source: youtube-dl-gui
>Target Site: System.String GetYoutubeDlVersion(Int32)
>Full report:
>System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at youtube_dl_gui.UpdateChecker.GetYoutubeDlVersion(Int32 GitID)

and

>rtbExceptionDetails
>
>A web exception occured
>Message: The request was aborted: The connection was closed unexpectedly.
>Stacktrace:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
>   at System.Net.WebClient.DownloadFile(String address, String fileName)
>   at youtube_dl_gui.UpdateChecker.<>c__DisplayClass1.<UpdateYoutubeDl>b__0()
>Source: System
>Target Site: Void DownloadFile(System.Uri, System.String)
>Inner Exception: 
>Response: 
>Web Address: 
>Full report:
>System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
>   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
>   at System.Net.WebClient.DownloadFile(String address, String fileName)

**also, yt-dlp.exe is just deleted on each update attempt (?)**

**Comment by murrty** [comment]
Yes, if the YtdlType setting is out of the accepted array (0, 1, 2) it should default to youtube-dl. Since it kept going OUT of the array anyway, it will always download youtube-dl.

I tried it out and it looks fixed on my end, but can you try it on yours with this build?
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/6932254/youtube-dl-gui.zip)

**Comment by plissken1138** [comment]
working fine now. cheers!

and thanks for including dlp fork.

**Comment by murrty** [comment]
that's good to hear.

i am hoping to add more forks, but dlc and dlp are the most common ones at this time.
