### ISSUE TITLE
Broken formatting of downloaded files

### ISSUE THREAD

**Issue by exoticflower85** [murrty/youtube-dl-gui#98]
When I download videos from Youtube, the video files look like this
`"C:\Users\Me\Downloads# -f bestvideo[ext=mp4]+bestaudio[ext=m4a]\best[ext=mp4] --ffmpeg-location D#\ffmpeg\bin\ffmpeg.exe --hls-prefer-ffmpeg"`
How to tell your program to download videos in "Downloads" folder without any classification? Thank you.

**Comment by murrty** [comment]
The files are named like that?

What do you mean by downloading without classification?

**Comment by exoticflower85** [comment]
Yes.
Without classification = without grouping downloaded files into separate folders by site, quality and the like

**Comment by murrty** [comment]
Can you send me your settings.ini file?

**Comment by exoticflower85** [comment]
Where is it? I only found this file that looks like settings
user.config
[user.txt](https://github.com/murrty/youtube-dl-gui/files/6980551/user.txt)

**Comment by murrty** [comment]
Hey, so looking through this, you haven't actually set a file name schema. that's why it's downloading like that. You can do that in the settings, and select a pre-made one.
